[build]
  command = "npm run build"
  publish = ".next"

# Basic form processing settings
[build.processing.html]
  pretty_urls = true

# Handle static form submissions - this is critical for Next.js
[[redirects]]
  from = "/__forms.html"
  to = "/__forms.html"
  status = 200
  force = true

# Ensure all paths route correctly for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false 